=== ManhDungNg/NHOM5-DOANCHUYENNGANH/BE/Bai1/Class.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Class"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

	<xs:simpleType name="sidType">
		<xs:restriction base="xs:string">

			<xs:pattern value="S\d{4,8}"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="nameType">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="markType">
		<xs:restriction base="xs:double">

			<xs:minInclusive value="0.0"/>
			<xs:maxInclusive value="10.0"/>
		</xs:restriction>
	</xs:simpleType>


	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="student" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sid" type="sidType"/>
							<xs:element name="name" type="nameType"/>
							<xs:element name="dob" type="xs:date"/>
							<xs:element name="mark" type="markType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== ManhDungNg/NHOM5-DOANCHUYENNGANH/BE/Bai1/Class.xml
<?xml version="1.0" encoding="utf-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="Class.xsd">

	<student>
		<sid>S1234</sid>
		<name>Nguyen Van A</name>
		<dob>2002-05-15</dob>
		<mark>8.5</mark>
	</student>

	<student>
		<sid>S2023602</sid>
		<name>Tran Thi B</name>
		<dob>2003-11-20</dob>
		<mark>9.0</mark>
	</student>

</class>
